# =============================================================================
# Linker Frontend — Dockerfile (AWS / ECR + App Runner)
# Next.js 14 with App Router + NextAuth + Tailwind CSS
# =============================================================================
# Multi-stage build:
#   Stage 1 (builder) — install deps, build Next.js in standalone mode
#   Stage 2 (production) — minimal image with only the standalone server
#
# ⚠️  IMPORTANT — NEXT_PUBLIC_* environment variables:
#   Next.js bakes any NEXT_PUBLIC_* variable into the JS bundle at build time.
#   These values are visible in the browser. They CANNOT be changed at runtime.
#   You MUST pass them as --build-arg during `docker build`.
#
#   This means: if you change NEXT_PUBLIC_API_URL, you must rebuild the image.
#   The CI/CD pipeline handles this automatically via build-args in the workflow.
# =============================================================================

ARG NODE_VERSION=20-alpine

# ---- Stage 1: Builder ----
FROM node:${NODE_VERSION} AS builder

# libc6-compat: Alpine compatibility layer (needed by some native npm modules)
RUN apk add --no-cache libc6-compat curl

WORKDIR /app

# Copy package files first (Docker layer cache optimization)
COPY package*.json ./

# Install all dependencies including devDeps needed for the build
RUN npm ci

# Copy all source code
COPY . .

# ── Build-time environment variables ─────────────────────────────────────────
# These are passed via --build-arg in the GitHub Actions workflow.
# They get embedded into the JavaScript bundle by Next.js compiler.

# The URL of your deployed NestJS backend API
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# The public URL of this frontend (required by NextAuth.js for callbacks)
ARG NEXTAUTH_URL
ENV NEXTAUTH_URL=${NEXTAUTH_URL}

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Build the Next.js app
# Requires next.config.mjs to have: output: 'standalone'
# Produces:
#   .next/standalone/  → self-contained production server
#   .next/static/      → CSS, JS chunks, image assets
#   public/            → static files (favicon, robots.txt, etc.)
RUN npm run build


# ---- Stage 2: Production ----
FROM node:${NODE_VERSION} AS production

RUN apk add --no-cache curl

WORKDIR /app

# ✅ Security: Run as non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy the standalone Next.js server (self-contained, no node_modules needed)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy compiled static assets into the right path
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy public directory (favicons, robots.txt, og images, etc.)
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

# App Runner requires the server to listen on 0.0.0.0 (all interfaces),
# not just localhost (127.0.0.1)
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1

# server.js is generated by Next.js when output: 'standalone' is set
CMD ["node", "server.js"]
